### PR TITLE
Mostly removing deprecations

### PR DESCRIPTION
**Pull request by bieron**
Hello!

I realize this code is 4 years old, so this might come as a surprise. In the meantime some stuff became deprecated, so I focused on bringing your module up and running on current perl version.
I divided changes into separate commits in case you decide you do not want some changes.

P.S. Your repository was assigned to me in CPAN 2015 Pull Request Challenge.
http://cpan-prc.org/
You might consider to participate :)

### CODE REVIEW

**Comment by nothingmuch** [comment]
Hi, and thanks!

Do you use this? If so would you like CPAN rights for this code?

p.s. the shebang was for the benefit of a text editor, but I can't remember if vim actually was that stupid... wow this was ages ago =P

**Comment by bieron** [comment]
Hi,

no, I don't use it, I only got it as an assignment. But what I've noticed
is that the git repo is out of date (0.06) comparing to CPAN (0.08). Also,
CPAN page (https://metacpan.org/release/POE-Component-Supervisor) belongs
to a Matt S Trout - is that your name/alias/co-admin? Or am I missing
something?
I think the best way would be to update your repo to CPAN's 0.08, and then
you'll decide whether or not to merge my pull request. What do you think?

Cheers,
Jan Bieroń

2015-05-11 22:49 GMT+02:00 Yuval Kogman notifications@github.com:

**Comment by karenetheridge** [comment]
The last two releases were made by @shadowcat-mst, but he didn't update the metadata to point to his repository.

Lately I've been curating @nothingmuch's releases that collect new tickets/pull requests -- I didn't see this pull request sooner because no ticket was added to its RT queue (where all maintainers get notification, rather than just the owner of the individual repository).  It's a simple enough matter for me to sync up with Matt's changes, rebase this PR and then release it.  I see that some of the changes in this PR were already made in 0.08.

**Comment by bieron** [comment]
> It's a simple enough matter for me to sync up with Matt's changes, rebase
> this PR and then release it.
> 
> That would be great. Thanks!

**Comment by karenetheridge** [comment]
Merged and released!  This ticket can now be closed.

**Pull request closed without merging**
